namespace :upwork do
  desc 'Update the list of available categories and subcategories'
  task fetch_categories_and_subcategories: :environment do
    lead_fields = {
      'active_assignments_count' => 'cf_leads_upworkactiveassignmentscount',
      'avg_hourly_jobs_rate' => 'cf_leads_upworkavghourlyjobsrate',
      'cf_894' => 'cf_leads_technologies',
      'cf_898' => 'cf_leads_upworkid',
      'cf_906' => 'cf_leads_facebook',
      'cf_908' => 'cf_leads_linkdin',
      'cf_910' => 'cf_leads_skype',
      'cf_912' => 'cf_leads_upworkcontractdate',
      'cf_918' => 'cf_leads_upworkhourscount',
      'cf_928' => 'cf_leads_upworktotalcharges',
      'cf_930' => 'cf_leads_upworktotalassignments',
      'cf_932' => 'cf_leads_upworkactiveassignmentscount',
      'cf_934' => 'cf_leads_upworkopencount',
      'cf_936' => 'cf_leads_upworkscore',
      'cf_938' => 'cf_leads_upworkavghourlyjobsrate',
      'city' => 'city',
      'code' => 'code',
      'company' => 'company',
      'contract_date' => 'cf_leads_upworkcontractdate',
      'country' => 'country',
      'description' => 'description',
      'designation' => 'designation',
      'email' => 'email',
      'fax' => 'fax',
      'feedback_count' => 'cf_leads_upworkfeedbackcount',
      'filled_count' => 'cf_leads_upworkfilledcount',
      'firstname' => 'firstname',
      'hours_count' => 'cf_leads_upworkhourscount',
      'industry' => 'industry',
      'lane' => 'lane',
      'lastname' => 'lastname',
      'lead_no' => 'lead_no',
      'leadstatus' => 'leadstatus',
      'mobile' => 'mobile',
      'open_count' => 'cf_leads_upworkopencount',
      'phone' => 'phone',
      'pobox' => 'pobox',
      'posted_count' => 'cf_leads_upworkpostedcount',
      'salutationtype' => 'salutationtype',
      'state' => 'state',
      'website' => 'website'
    }
  end
end
