:verbose:     true
:pidfile:     ./tmp/pids/sidekiq.pid
:logfile:     ./log/sidekiq.log
:concurrency: 15
:queues:
  - [upwork_opening_uid, 1]
  - [upwork, 9]
:schedule:
  Upwork::FetchProxiesJob:
    every: '10m'
  Upwork::FetchJobsJob:
    every: '10m'
